name: benchmark
on:
  # makes workflow reusable
  workflow_call:
    inputs:
      benchmark_script:
        description: "path to the benchmark script"
        type: string
        required: true

permissions:
  contents: write

jobs:
  benchmark:
    name: benchmark 
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: Run benchmark
        run: python3 ${{ inputs.benchmark_script }} -o output_py_bench.txt
      - name: Store benchmark result pybench
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'customBiggerIsBetter'
          # Where the output from the benchmark tool is stored
          output-file-path: output_py_bench.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-always: true
          comment-on-alert: true
          fail-on-alert: true
          auto-push: true
          alert-threshold: 10
          gh-pages-branch: "gh-pages"

