name: benchmark
on:
  # makes workflow reusable
  workflow_call:
    inputs:
      benchmark_script:
        description: "path to the benchmark script"
        type: string
        required: true

jobs:
  benchmark:
    name: benchmark 
    runs-on: ubuntu-latest
    outputs:
      artifact_name: ${{ steps.set_artifact_name.outputs.artifact_name}}

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Run benchmark
        run: python3 ${{ inputs.benchmark_script }} -o output_py_bench.txt

      - name: set artifact name
        id: set_artifact_name
        run: |
          ARTIFACT_NAME=`echo "${{ github.run_id}}-${{ inputs.benchmark_script }}" | tr '/' '_'`
          echo "artifact_name=$ARTIFACT_NAME" >>$GITHUB_OUTPUT

      # upload artifact
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.set_artifact_name.outputs.artifact_name}} 
          path: output_py_bench.txt
          retention-days: 1

  # call the benchmark action store workflow
  push_to_gh_pages:
    if: ("${{ inputs.benchmark_script == 'src/py_bench.py' }}" == "true")
    needs: benchmark 
    uses: ./.github/workflows/push-to-ghpages.yml
    with:
      artifact_id: ${{ needs.benchmark.outputs.artifact_name }}
      tool: "customBiggerIsBetter"
      file_name: output_py_bench.txt
