name: benchmark
on:
  # makes workflow reusable
  workflow_call:
    inputs:
      benchmark_script:
        description: "path to the benchmark script"
        type: string
        required: true

env:
   ARTIFACT_NAME:`echo "${{ github.run_id}}-${{ inputs.benchmark_script }}" | tr '/' '_'`

jobs:
  benchmark:
    name: benchmark 
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Run benchmark
        run: python3 ${{ inputs.benchmark_script }} -o output_py_bench.txt

      # upload artifact
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME}}
          path: output_py_bench.txt
          retention-days: 1

  # call the benchmark action store workflow
  push_to_gh_pages:
    needs: benchmark 
    uses: ./.github/workflows/push-to-ghpages.yml
    with:
      artifact_id: ${{ env.ARTIFACT_NAME }}
      tool: "CustomBiggerIsBetter"
      file_name: output_py_bench.txt
