name: GHA bench test
on:
  push:
    branches:
      - main 
jobs:
  permissions:
    contents: write
  benchmark:
    strategy:
      matrix:
        py_bench_scripts: ['src/py_bench.py', 'src/py_bench2.py']
    uses: ./.github/workflows/benchmark.yml
    with:
      benchmark_script: ${{ matrix.py_bench_scripts }}

