name: GHA bench test
on:
  push:
    branches:
      - main 
permissions:
  contents: write
jobs:
  benchmark:
    strategy:
      matrix:
        py_bench_scripts: ['src/metrics.py']
        gh_tools: ['customBiggerIsBetter', 'customSmallerIsBetter']
    uses: ./.github/workflows/benchmark.yml
    with:
      benchmark_script: ${{ matrix.py_bench_scripts }}
      gh_tool: ${{ matrix.gh_tools }}

