name: GHA bench test
on:
  push:
    branches:
      - main 
jobs:
  benchmark:
    name: benchmark 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run py_bench
        uses: '.github/workflows/benchmark.yml'
        with:
          benchmark_script: 'src/py_bench.py'
      - name: Run py_bench2
        uses: '.github/workflows/benchmark.yml'
        with:
          benchmark_script: 'src/py_bench2.py'
