name: GHA bench test
on:
  push:
    branches:
      - main 
jobs:
  benchmark:
    name: benchmark 
    runs-on: ubuntu-latest
    #permissions:
    #  # deployments permission to deploy GitHub pages website
    #  deployments: write
    #  # contents permission to update benchmark contents in gh-pages branch
    #  contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Run benchmark
        run: python3 src/py_bench.py -o output.txt
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          # What benchmark tool the output.txt came from
          tool: 'customBiggerIsBetter'
          # Where the output from the benchmark tool is stored
          output-file-path: output.txt
          #github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: false
          #gh-pages-branch: "gh-pages"
      - name: Push bm result
        run: git push 'https://varun-sundar-rabindranath:${{ secrets.GITHUB_TOKEN }}@github.com/varun-sundar-rabindranath/gha-bench-test.git' gh-pages:gh-pages
