name: push to ghpages
on: 
  # makes workflow reusable
  workflow_call:
    inputs:
      out_file:
        description: "path to the output file"
        type: string
        required: true


jobs:
  push-to-ghpages:
    name: push to ghpages 
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Run benchmark
        run: |
          python3 src/py_bench.py -o output_py_bench.txt
          python3 src/py_bench2.py -o output_py_bench2.txt
      - name: Store benchmark result pybench1
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'customBiggerIsBetter'
          # Where the output from the benchmark tool is stored
          output-file-path: output_py_bench.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: false
          comment-always: true
          auto-push: true
          gh-pages-branch: "gh-pages"

      - name: Store benchmark result pybench2
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'customBiggerIsBetter'
          # Where the output from the benchmark tool is stored
          output-file-path: output_py_bench2.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: false
          comment-always: true
          auto-push: true
          gh-pages-branch: "gh-pages"
