name: push to ghpages
on: 
  # makes workflow reusable
  workflow_call:
    inputs:
      artifact_id:
        description: "id of the benchmark results artifact"
        type: string
        required: true
      tool:
        description: "gh benchmark tool name"
        type: string
        required: true
      file_name:
        description: "file to upload"
        type: string
        required: true

jobs:
  push-to-ghpages:
    name: push to ghpages 
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: download benchmark results artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_id}}
          path: downloads 

      - name: Display structure of downloaded files
        run: ls -R ./downloads

      - name: push to gh pages
        uses: .github/actions/custom-gh-action-benchmark/action.yml
        with:
          gh_action_benchmark_json_file_path:  "downloads/${{ inputs.file_name }}"
          gh_action_benchmark_tool: ${{ inputs.tool }}
          gh_pages_branch: "benchmark-gh-pages-testing"
          save_data_file: "true"
          auto_push: "true"

      #- name: push to gh pages 
      #  uses: benchmark-action/github-action-benchmark@v1
      #  with:
      #    tool: ${{ inputs.tool }} 
      #    # Where the output from the benchmark tool is stored
      #    output-file-path: "downloads/${{inputs.file_name}}"
      #    github-token: ${{ secrets.GITHUB_TOKEN }}
      #    comment-always: true
      #    auto-push: true
      #    gh-pages-branch: "benchmark-gh-pages-testing"
