name: push to ghpages
on: 
  # makes workflow reusable
  workflow_call:
    inputs:
      artifact_id:
        description: "id of the benchmark results artifact"
        type: string
        required: true
      tool:
        description: "gh benchmark tool name"
        type: string
        required: true
      file_name:
        description: "file to upload"
        type: string
        required: true

jobs:
  push-to-ghpages:
    name: push to ghpages 
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: download benchmark results artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.benchmark_results_artifact_id }}
          path: .

      - name: push to gh pages 
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: ${{ inputs.tool }} 
          # Where the output from the benchmark tool is stored
          output-file-path: "${{ inputs.benchmark_results_artifact_id }} / ${{inputs.file_name}}"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-always: true
          auto-push: true
          gh-pages-branch: "benchmark-gh-pages-testing"
